#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Bootstrap\RegisterProviders;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/../autoload.php';

$psr4 = [
    "Barryvdh\\LaravelIdeHelper\\" => __DIR__.'/vendor/barryvdh/laravel-ide-helper/src',
    "Barryvdh\\Reflection\\" => __DIR__.'/vendor/barryvdh/reflection-docblock/src/Barryvdh/Reflection',
    "Composer\\ClassMapGenerator\\" => __DIR__ . '/vendor/composer/class-map-generator/src',
    "Composer\\Pcre\\" => __DIR__ . '/vendor/composer/pcre/src',
];

spl_autoload_register(function ($class) use ($psr4) {
    foreach ($psr4 as $namespace => $src) {
        if (str_starts_with($class, $namespace)) {
            $file = $src . '/' . str_replace([$namespace, '\\'], ['', '/'], $class) . '.php';

            if (is_file($file)) {
                require_once $file;
            }

            break;
        }
    }
});

/** @var Application $app */
$app = require_once __DIR__.'/../../bootstrap/app.php';

$app->booted(function () {
    Artisan::command('support', function (Application $app) {
        $this->call('ide-helper:generate', ['--ansi' => true]);
        $this->call('ide-helper:meta', ['--ansi' => true]);
        $this->call('ide-helper:models', ['--ansi' => true, '--nowrite' => true]);
        foreach ([
            '.phpstorm.meta.php',
            '_ide_helper.php',
            '_ide_helper_models.php',
        ] as $file) {
            if (file_exists(__DIR__ . '/' . $file)) {
                File::move(__DIR__ . '/' . $file, $app->basePath($file));
            }
        }
    });
});

$app->afterBootstrapping(RegisterProviders::class, function (Application $app) {
    $app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
});

// Bootstrap Laravel and handle the command...
$status = $app->handleCommand(new ArgvInput);

exit($status);
